### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by Asarria081** [adrigzr/badconga#2]
Hola.
He instalado el repositorio desde HACS, he copiado la carpeta badconga en mi directorio de custom components y he introducido el código propuesto en mi configuration.yaml.
Pero cuando verifico la configuración, antes de reiniciar, el sistema se queda colgado y tengo que anular el código de configuration.

**Comment by Woful** [comment]
> Hola.
> He instalado el repositorio desde HACS, he copiado la carpeta badconga en mi directorio de custom components y he introducido el código propuesto en mi configuration.yaml.
> Pero cuando verifico la configuración, antes de reiniciar, el sistema se queda colgado y tengo que anular el código de configuration.

Hola, ¿qué error se muestra? ¿Ha puesto su 'password' y su 'email' entre comillas?

**Comment by Asarria081** [comment]
Ok. Solucionado. Estaba usando la misma cuenta en la app Conga 3000 y en la configuración de HA. Cerrando la sesión en la app  ha funcionado en HA. Supongo que lo mejor será crear una cuenta para la app y otra para HA. Por cierto, ¿me puedes orientar sobre el tipo de tarjetas que has utilizado para ambas entidades?

**Comment by adrigzr** [comment]
Hola @Asarria081,

Me alegro que lo solucionaras. No obstante, recuerda que el plugin está en modo experimental y seguramente de otros errores o sea inestable.

Sobre las tarjetas: para el mapa he usado el [`picture-entity`](https://www.home-assistant.io/lovelace/picture-entity/) y para la aspiradora recomiendo la [`vacuum-card`](https://github.com/denysdovhan/vacuum-card) que se puede encontrar en HACS, muy chula.

Te dejo por aquí un ejemplo de configuración:

```
entity: vacuum.conga
image: default
stats:
  cleaning:
    - attribute: clean_size
      subtitle: Cleaning area
      unit: cm2
    - attribute: clean_time
      subtitle: Cleaning time
      unit: minutes
type: 'custom:vacuum-card'
```

![](https://user-images.githubusercontent.com/3459374/83282788-c9e30280-a1e2-11ea-8e13-6208169ddc0a.png)
